debuging .env creation

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -20,6 +20,12 @@ jobs:
           echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ env.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
           echo "VITE_FIREBASE_APP_ID=${{ env.FIREBASE_APP_ID }}" >> .env
           echo "VITE_FIREBASE_MEASUREMENT_ID=${{ env.FIREBASE_MEASUREMENT_ID }}" >> .env
+      - name: Debug .env file
+        run: |
+          pwd
+          ls -la
+          echo "Content of .env file:"
+          cat .env || echo ".env file not found"
 
       - run: npm ci && npm run build
       - uses: FirebaseExtended/action-hosting-deploy@v0
